// Shared department and doctor data extracted for reuse.

const List<String> kDepartments = [
  "Conservative Dentistry & Endodontics",
  "Oral & Maxillofacial Surgery",
  "Oral Medicine & Radiology",
  "Oral Pathology & Microbiology",
  "Orthodontics & Dentofacial Orthopedics",
  "Pediatric and Preventive Dentistry",
  "Periodontology",
  "Prosthodontics and Crown & Bridge",
  "Public Health Dentistry",
];

const Map<String, List<String>> kDepartmentDoctors = {
  "Periodontology": [
    "Dr. Vineet Kini",
    "Dr. Sarika Shetty",
    "Dr. Sujeet Khiste",
    "Dr. Bharat Gupta",
    "Dr. Trupti Naykodi",
    "Dr. Agraja Patil",
  ],
  "Conservative Dentistry & Endodontics": [
    "Dr. Sumanthini M. V.",
    "Dr. Anuradha Patil.",
    "Dr. Divya Naik",
    "Dr. Jayeeta Verma",
    "Dr. Shouvik Mandal",
    "Dr. Antara Ghosh",
    "Dr. Aditya Shinde",
    "Dr. Jimish Shah",
    "Dr. Tanvi Satpute",
    "Dr. Shreshtha Mukherjee",
    "Dr. Manasi Surwade",
    "Dr. Manisha Bhosle",
  ],
  "Oral & Maxillofacial Surgery": [
    "Dr. Srivalli Natarajan",
    "Dr. Usha Asnani",
    "Dr. Sunil Sidana",
    "Dr. Adil Gandevivala",
    "Dr. Suraj Ahuja",
    "Dr. Sneha Naware",
    "Dr. Nitesh Patkar",
    "Dr. Padmakar Baviskar",
    "Dr. Ruchita Balkawade",
    "Dr. Pareeksit Bagchi",
    "Dr Meghna Chandrachood",
    "Dr. Dr. Pranave P",
    "Dr. Varsha Patel",
  ],
  "Oral Medicine & Radiology": [
    "Dr. Rohit Gadda",
    "Dr. Neha Patil",
    "Dr. Priyanka Tidke",
    "Dr Isha Mishra",
    "Dr. Manjari Chaudhary",
    "Dr. Munitha Naik",
  ],
  "Oral Pathology & Microbiology": [
    "Dr. Shilpa C. Patel",
    "Dr. Jigna Pathak",
    "Dr. Kamlesh Dekate",
    "Dr. Niharika Swain",
    "Dr. Rashmi Hosalkar",
    "Dr. Shraddha Ghaisas",
    "Dr. Yogita Penkar",
  ],
  "Orthodontics & Dentofacial Orthopedics": [
    "Dr. Ravindranath V. K.",
    "Dr. Anjali Gheware",
    "Dr. Amol Mhatre",
    "Dr. Pradnya Korwar",
    "Dr. Neeraj Kolge",
    "Dr. Saurabh Waghchaure",
  ],
  "Pediatric and Preventive Dentistry": [
    "Dr. Shrirang Sevekar",
    "Dr. Jha Mihir Kumar",
    "Dr Sayli Vichare",
    "Dr Harsh Sachdev",
    "Dr. Ashwini Avanti",
    "Dr. Devanshi Shah",
    "Dr. Sujata Hirave",
    "Dr. Rupali Deshmukh",
  ],
  "Prosthodontics and Crown & Bridge": [
    "Dr. Jyoti Nadgere",
    "Dr. Janani Iyer",
    "Dr Neelam Ashok Salvi",
    "Dr. Saumil C. Sampat",
    "Dr. Anuradha Mohite",
    "Dr. Prachiti Terni",
    "Dr. Bhoomi Parmar",
    "Dr Pooja Sambhaji Kakade",
    "Dr. Madhura Titar",
    "Dr. Ragini Sanaye",
    "Dr. Shruti Potdukhe",
    "Dr. Kashmira pawar",
    "Dr. Kanchan S Sahwal",
    "Dr. Khizer Syed",
    "Dr. Mangesh Jadhav",
  ],
  "Public Health Dentistry": [
    "Dr. Vaibhav Pravin Thakkar",
    "Dr. Deeksha Shetty",
    "Dr. Pankaj Londhe",
    "Dr. Rafeeq Nalband",
    "Dr. Mausami Malgaonkar",
    "Dr. Kashmira Kadam",
  ],
};
